### ISSUE TITLE
Separate QueueManager into two services

### ISSUE THREAD

**Issue by zlikavac32** [treehouselabs/worker-bundle#12]
Would it make sense to split QueueManager into two services, one responsible for queuing  and other for managing workers?

Use case is queueing new jobs from an existing worker. Currently regular use has circular references in container when injecting queue manager into executor

**Comment by pkruithof** [comment]
Sure, go for it 💪 

It would need to be managed in a BC way though. So after splitting it up in services, the queue manager should maintain it's functionality in this major version, by delegating calls to the new services. Then, in the next major version, we can drop support for this. In the meantime, you can use the new services in your application.

**Comment by zlikavac32** [comment]
@pkruithof My idea exactly :). Will check it out and see what can be done.

Just a small question, do you mind if phpspec is included into project for writing unit tests or should I use phpunit for those tests?

**Comment by pkruithof** [comment]
If it is better suited, I don't mind. phpspec is great :)

**Comment by zlikavac32** [comment]
@pkruithof Changing QueueManager to orient towards new services is BC change since that would alter constructor so perhaps this can only be done in next major version?

Anyhow, I'll have some code to show soon so you can comment it out.

**Comment by pkruithof** [comment]
The constructor is not part of the public API, in my opinion. So I wouldn't constitute it as a BC break.

**Comment by zlikavac32** [comment]
@pkruithof Ok if it's not considered to be public API, but note that queue manager right now does not have any interface, so only way to modify behaviour is to extend it thus inheriting constructor (I know I did it) :)

**Comment by pkruithof** [comment]
It could potentially break extending classes, I realize this. However extending can be done without inheriting constructor, of course.

**Comment by pkruithof** [comment]
Sorry, I did not look at your refactor PR at the time. Thanks for your effort though 🙌 

I'm deprecating and archiving the project, see [the readme](https://github.com/treehouselabs/worker-bundle#deprecated--archived) for details and instructions
