### ISSUE TITLE
Inspect Command should use peek_* methods

### ISSUE THREAD

**Issue by mvanduijker** [treehouselabs/worker-bundle#5]
Instead of reserving and releasing back on the queue.

With the peek methods we can also easily get stats from buried jobs.

https://github.com/earl/beanstalkc/blob/master/TUTORIAL.mkd#inspecting-jobs

**Comment by pkruithof** [comment]
The problem there is that we don't have the id's to give to the peek command. I agree it's a rather nasty solution, the way it's done right now, but I don't know a better alternative.

**Comment by mvanduijker** [comment]
If I read the documentation correctly, you can inspect jobs without id by peeking according to their state with peek_ready, peek_delayed and peek_burried.

**Comment by pkruithof** [comment]
But you always get the first job for that state, right? The inspect command allows you to inspect a certain number of jobs, or all of them.

**Comment by mvanduijker** [comment]
Hmm that is right. It is now really hard to debug burried jobs. Maybe add a command to peek in first burried job? So we can more easily find the troubled job in the logs and kick it back when solved.

**Comment by pkruithof** [comment]
Good idea, `worker:peek`?

Also, maybe we should make the inspect command give a warning about its method, and ask for confirmation before continuing.

**Comment by mvanduijker** [comment]
:+1:

**Comment by pkruithof** [comment]
See #6

**Comment by pkruithof** [comment]
Implemented in #6
