### ISSUE TITLE
When receive support for SF3?

### ISSUE THREAD

**Issue by nkl90** [treehouselabs/worker-bundle#7]
Hello we used your bundle on SF 2.8, how I can install this bundle on Symfony 3 and higher?

**Comment by nkl90** [comment]
Sorry, I view changelog. I install this for SF3 so:
`composer require treehouselabs/worker-bundle dev-master`

**Comment by pkruithof** [comment]
Apologies, version 1.2.0 (which adds support for Symfony 2.8 and 3.0) was added to the changelog, but not actually made. I just created that release, so you can require `"treehouselabs/worker-bundle": "^1.2.0"` as of now.

**Comment by fesor** [comment]
Can this be closed?

**Comment by pkruithof** [comment]
Yes.
