### ISSUE TITLE
Timeout for workers?

### ISSUE THREAD

**Issue by fesor** [treehouselabs/worker-bundle#8]
> [2016-06-03 09:23:07] Waiting at most 60 seconds for a reserved job...

I want to ask, is there any reason to hardcode timeout for workers? Why not just wait for tasks?

**Comment by pkruithof** [comment]
I personally prefer to not keep PHP scripts running indefinitely, though making this an option would be fine for me.

**Comment by mikrahub** [comment]
hi, could someone explain how to set timeout?
 https://github.com/treehouselabs/worker-bundle/pull/11 

  The "--timeout" option does not exist

**Comment by pkruithof** [comment]
I just released 1.2.1 which contains this PR, you can update the dependency to get it.
